# Taken from https://github.com/dotnet/dotnet-docker/blob/main/samples/dotnetapp/README.md

FROM mcr.microsoft.com/dotnet/framework/sdk AS build
WORKDIR /source
EXPOSE 80

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
RUN dotnet publish -c release -o /app --no-restore --no-cache

# final stage/image
FROM mcr.microsoft.com/dotnet/framework/aspnet
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "SimpleApi.dll"]
