name: Docker Image CI

env:
  AZ_ACR_NAME: aksd01acr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${ secrets.AZ_SP_CLIENT_ID }
        # Container registry password
        password: ${ secrets.AZ_SP_CLIENT_SECRET }
        # Container registry server url
        login-server: ${ secrets.AZ_ACR_NAME }
    - name: Build the Docker image
      run: docker build . --file Dockerfile-linux --tag ${ env.AZ_ACR_NAME }.azureacr.io/randommultiplications:linux-latest #$(date +%s)
    - name: Push Image to ACR
      run: docker push ${ env.AZ_ACR_NAME }.azureacr.io/randommultiplications:linux-latest
