name: Build Image and Push to ACR (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.AZ_SP_CLIENT_ID }}
        # Container registry password
        password: ${{ secrets.AZ_SP_CLIENT_SECRET }}
        # Container registry server url
        login-server: ${{ secrets.AZ_ACR_NAME }}.azurecr.io
    - name: Build the Docker image
      run: docker build . --file Dockerfile-linux --tag ${{ secrets.AZ_ACR_NAME }}.azurecr.io/randommultiplications-windows:latest #$(date +%s)
    - name: Push Image to ACR
      run: docker push ${{ secrets.AZ_ACR_NAME }}.azurecr.io/randommultiplications-windows:latest
